# Generated by Django 3.2.15 on 2023-09-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230916_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
