# Generated by Django 3.2.15 on 2023-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_historicalstock_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
