# Generated by Django 3.2.15 on 2023-09-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
