# Generated by Django 3.2.15 on 2023-09-15 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Register created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestampt')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deleted timestamp', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicate if the register is active')),
                ('number', models.CharField(max_length=16)),
                ('exp_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('name_on_card', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Register created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestampt')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deleted timestamp', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicate if the register is active')),
                ('type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.account')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.card')),
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
    ]
